### ISSUE TITLE
Bug sur la fonction "supprimer un collaborateur" pour un projet

### ISSUE THREAD

**Issue by cyrilletoulet** [MesoNET/gramc-meso#78]
Dans **Demandeur**" / **Projet** M[AA][NNN] / **Collaborateurs**, cocher la case "**supprimer**" puis cliquer sur  "**Sauvegarder**" ne change rien sur l'interface web, ni en base de données (d'après l'API, les champs "deleted" restent à false). 

Il y a un bug sur la fonction supprimer qui devrait à minima mettre le flag API à deleted et griser la ligne dans les collaborateurs et garder la case "supprimer" coché.

**Comment by Benjamin-Bill** [comment]
problème résolue ( le formulaire utilisé ne renvoyait pas les données concernant le checkbox supprimé et le script s'occupant du traitement du résultat ne prévoyait pas le cas de la suppression )
